services:
  pg15-repl-source:
    build:
      context: .
    image: postgres:${PGVERSION}
    container_name: ${CONTAINER_NAME_PREFIX}-source
    command: [ "postgres", "-c", "config_file=/etc/postgres.conf" ]
    environment:
      PGDATA: ${PGDATA_BASEDIR}/source
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - source:${PGDATA_BASEDIR}/source
      - ${PWD}/postgres.conf:/etc/postgres.conf
      - ${PWD}/sql:/opt/sql
    ports:
      - ${SOURCE_PORT}:5432
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  pg15-repl-target:
    build:
      context: .
    image: postgres:${PGVERSION}
    container_name: ${CONTAINER_NAME_PREFIX}-target
    command: [ "postgres", "-c", "config_file=/etc/postgres.conf" ]
    environment:
      PGDATA: ${PGDATA_BASEDIR}/source
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - target:${PGDATA_BASEDIR}/target
      - ${PWD}/postgres.conf:/etc/postgres.conf
      - ${PWD}/sql:/opt/sql
    ports:
      - ${TARGET_PORT}:5432
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  source:
  target:
